In [ ]:
# Dataframe 만들기

In [1]:
import pandas as pd

df = pd.DataFrame()

print(df)

Empty DataFrame
Columns: []
Index: []

In [27]:
import pandas as pd

lst = ['Geeks', 'For', 'Geeks', 'is', 
            'portal', 'for', 'Geeks']

df = pd.DataFrame(lst)
print(df)

        0
0   Geeks
1     For
2   Geeks
3      is
4  portal
5     for
6   Geeks

In [28]:
df.shape

(7, 1)

In [ ]:
df.dtypes

# 0    object
# dtype: object

# 컬럼 이름은 0, 타입은 object(문자열)

0    object
dtype: object

In [30]:
df.head()

        0
0   Geeks
1     For
2   Geeks
3      is
4  portal

In [31]:
df.tail()

        0
2   Geeks
3      is
4  portal
5     for
6   Geeks

In [32]:
df.head(3)

       0
0  Geeks
1    For
2  Geeks

In [33]:
df.tail(3)

        0
4  portal
5     for
6   Geeks

In [35]:
import numpy as np
import pandas as pd

data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
df = pd.DataFrame(data, columns=['A', 'B', 'C'])
print(df)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [37]:
# 'A' 컬럼을 가져와서 타입 확인
column_a = df['A']
print(f"'A' 컬럼의 타입: {type(column_a)}")

'A' 컬럼의 타입: <class 'pandas.core.series.Series'>

In [40]:
print(column_a)
print('-'*100)
print(column_a.index)
print('-'*100)
print(list(column_a.index))

0    1
1    4
2    7
Name: A, dtype: int64
----------------------------------------------------------------------------------------------------
RangeIndex(start=0, stop=3, step=1)
----------------------------------------------------------------------------------------------------
[0, 1, 2]

In [ ]:
df.dtypes
# 이 자체가 series
# df.dtypes를 요청하면 답을 Series 형태로 리턴한다는 의미


# A    int64
# B    int64
# C    int64
# 이 자체가 series가 되고 series의 값인 int64, int64, int64의 타입이 object라는 의미

A    int64
B    int64
C    int64
dtype: object

In [5]:
import pandas as pd

# initialize data of lists.
data = {'Name': ['Tom', 'nick', 'krish', 'jack'],
        'Age': [20, 21, 19, 18]}

# Create DataFrame
df = pd.DataFrame(data)

print(df)

    Name  Age
0    Tom   20
1   nick   21
2  krish   19
3   jack   18

In [4]:
import pandas as pd

dict = {'name':["aparna", "pankaj", "sudhir", "Geeku"],
        'degree': ["MBA", "BCA", "M.Tech", "MBA"],
        'score':[90, 40, 80, 98]}

df = pd.DataFrame(dict)

print(df)

     name  degree  score
0  aparna     MBA     90
1  pankaj     BCA     40
2  sudhir  M.Tech     80
3   Geeku     MBA     98

In [ ]:
# 인덱싱

In [47]:
import pandas as pd

data = {'Name': ['John', 'Alice', 'Bob', 'Eve', 'Charlie'],
        'Age': [25, 30, 22, 35, 28],
        'Gender': ['Male', 'Female', 'Male', 'Female', 'Male'],
        'Salary': [50000, 55000, 40000, 70000, 48000]}

df = pd.DataFrame(data)
print(df)
print(df.index)
# print(list(df.index))

      Name  Age  Gender  Salary
0     John   25    Male   50000
1    Alice   30  Female   55000
2      Bob   22    Male   40000
3      Eve   35  Female   70000
4  Charlie   28    Male   48000
RangeIndex(start=0, stop=5, step=1)

In [48]:
# Set 'Name' column as the index
df_with_index = df.set_index('Name')
print(df_with_index)

         Age  Gender  Salary
Name
John      25    Male   50000
Alice     30  Female   55000
Bob       22    Male   40000
Eve       35  Female   70000
Charlie   28    Male   48000

In [49]:
# Reset the index back to the default integer index
df_reset = df_with_index.reset_index()
print(df_reset)

      Name  Age  Gender  Salary
0     John   25    Male   50000
1    Alice   30  Female   55000
2      Bob   22    Male   40000
3      Eve   35  Female   70000
4  Charlie   28    Male   48000

In [50]:
# 한편 df_with_index는?
df_with_index

         Age  Gender  Salary
Name
John      25    Male   50000
Alice     30  Female   55000
Bob       22    Male   40000
Eve       35  Female   70000
Charlie   28    Male   48000

In [55]:
df_with_index.reset_index(inplace=True)
# inplace=True는 복사본을 만들지 않고 원본을 수정하라는 의미
df_with_index

      Name  Age  Gender  Salary
0     John   25    Male   50000
1    Alice   30  Female   55000
2      Bob   22    Male   40000
3      Eve   35  Female   70000
4  Charlie   28    Male   48000

In [56]:
# df_with_index = df.set_index('Name')

# 에러 발생
row = df_with_index.loc['Alice']
print(row)

KeyError: 'Alice'

In [57]:
df

      Name  Age  Gender  Salary
0     John   25    Male   50000
1    Alice   30  Female   55000
2      Bob   22    Male   40000
3      Eve   35  Female   70000
4  Charlie   28    Male   48000

In [ ]:
# row = df.loc['Alice']
df.loc[0]

# Name: 0의 의미는
# 이 Series는 원본 DataFrame의 인덱스 0번에서 가져온 데이터

Name       John
Age          25
Gender     Male
Salary    50000
Name: 0, dtype: object

In [59]:
# Set 'Age' as the new index
df_with_new_index = df.set_index('Age')
print(df_with_new_index)

        Name  Gender  Salary
Age
25      John    Male   50000
30     Alice  Female   55000
22       Bob    Male   40000
35       Eve  Female   70000
28   Charlie    Male   48000

In [ ]:
# 인덱스의 타입은 dtype='int64'
df_with_new_index.index

Index([25, 30, 22, 35, 28], dtype='int64', name='Age')

In [ ]:
# 인덱스의 타입은 dtype='int64'이므로 "30"이 아니라 30

df_with_new_index.loc[30]
# df_with_new_index.loc["30"]

Name       Alice
Gender    Female
Salary     55000
Name: 30, dtype: object

In [79]:
import pandas as pd

data = {'Name': ['John', 'Alice', 'Bob', 'Eve', 'Charlie'], 
        'Age': [25, 30, 22, 35, 28], 
        'Gender': ['Male', 'Female', 'Male', 'Female', 'Male'], 
        'Salary': [50000, 55000, 40000, 70000, 48000]}

df = pd.DataFrame(data)
print(df)

      Name  Age  Gender  Salary
0     John   25    Male   50000
1    Alice   30  Female   55000
2      Bob   22    Male   40000
3      Eve   35  Female   70000
4  Charlie   28    Male   48000

In [80]:
# iloc은 숫자 위치 (0에서 시작)
second_row = df.iloc[1]
print(second_row)

Name       Alice
Age           30
Gender    Female
Salary     55000
Name: 1, dtype: object

In [82]:
# df.loc[a:b]에서 b는 포함
# df.loc은 언제나 인덱스 레이블을 기준
print(df)
print("-"*100)
subset = df.loc[0:2, ['Name', 'Age']]
print(subset)

      Name  Age  Gender  Salary
0     John   25    Male   50000
1    Alice   30  Female   55000
2      Bob   22    Male   40000
3      Eve   35  Female   70000
4  Charlie   28    Male   48000
----------------------------------------------------------------------------------------------------
    Name  Age
0   John   25
1  Alice   30
2    Bob   22

In [ ]:
# 마스크
df['Age'] > 25

0    False
1     True
2    False
3     True
4     True
Name: Age, dtype: bool

In [ ]:
# 불리언 인덱싱
filtered_data = df[df['Age'] > 25]
print(filtered_data)

      Name  Age  Gender  Salary
1    Alice   30  Female   55000
3      Eve   35  Female   70000
4  Charlie   28    Male   48000

In [83]:
import pandas as pd

player_list = [['M.S.Dhoni', 36, 75, 5428000],
               ['A.B.D Villers', 38, 74, 3428000],
               ['V.Kohli', 31, 70, 8428000],
               ['S.Smith', 34, 80, 4428000],
               ['C.Gayle', 40, 100, 4528000],
               ['J.Root', 33, 72, 7028000],
               ['K.Peterson', 42, 85, 2528000]]

df = pd.DataFrame(player_list, columns=['Name', 'Age', 'Weight', 'Salary'])
print(df)

            Name  Age  Weight   Salary
0      M.S.Dhoni   36      75  5428000
1  A.B.D Villers   38      74  3428000
2        V.Kohli   31      70  8428000
3        S.Smith   34      80  4428000
4        C.Gayle   40     100  4528000
5         J.Root   33      72  7028000
6     K.Peterson   42      85  2528000

In [87]:
# loc[j:k]와 iloc[j:k]의 차이는 k가 포함되고 안되고
df1 = df.iloc[0:4]
print(df1)

print('-'*100)

# df.loc은 언제나 인덱스 레이블을 기준
print(list(df.index))

print('-'*100)

df2 = df.loc[0:4]
print(df2)

            Name  Age  Weight   Salary
0      M.S.Dhoni   36      75  5428000
1  A.B.D Villers   38      74  3428000
2        V.Kohli   31      70  8428000
3        S.Smith   34      80  4428000
----------------------------------------------------------------------------------------------------
[0, 1, 2, 3, 4, 5, 6]
----------------------------------------------------------------------------------------------------
            Name  Age  Weight   Salary
0      M.S.Dhoni   36      75  5428000
1  A.B.D Villers   38      74  3428000
2        V.Kohli   31      70  8428000
3        S.Smith   34      80  4428000
4        C.Gayle   40     100  4528000

In [71]:
df1 = df.iloc[:, 0:2]

print(df1)

            Name  Age
0      M.S.Dhoni   36
1  A.B.D Villers   38
2        V.Kohli   31
3        S.Smith   34
4        C.Gayle   40
5         J.Root   33
6     K.Peterson   42

In [89]:
print(df)

            Name  Age  Weight   Salary
0      M.S.Dhoni   36      75  5428000
1  A.B.D Villers   38      74  3428000
2        V.Kohli   31      70  8428000
3        S.Smith   34      80  4428000
4        C.Gayle   40     100  4528000
5         J.Root   33      72  7028000
6     K.Peterson   42      85  2528000

In [90]:
# iloc[a, b]에서 a는 행, b는 열의 위치를 선택
value = df.iloc[2, 3]  
print(value)

8428000

In [91]:
df

            Name  Age  Weight   Salary
0      M.S.Dhoni   36      75  5428000
1  A.B.D Villers   38      74  3428000
2        V.Kohli   31      70  8428000
3        S.Smith   34      80  4428000
4        C.Gayle   40     100  4528000
5         J.Root   33      72  7028000
6     K.Peterson   42      85  2528000

In [92]:
df.set_index('Name', inplace=True)
df

               Age  Weight   Salary
Name
M.S.Dhoni       36      75  5428000
A.B.D Villers   38      74  3428000
V.Kohli         31      70  8428000
S.Smith         34      80  4428000
C.Gayle         40     100  4528000
J.Root          33      72  7028000
K.Peterson      42      85  2528000

In [ ]:
# loc으로 특정 값 선택하기
# df.loc은 언제나 인덱스 레이블을 기준

value = df.loc['V.Kohli', 'Salary']
print(value)

8428000

In [2]:
import pandas as pd

# 샘플 데이터 생성
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Age': [25, 30, 35, 40, 45],
    'City': ['New York', 'London', 'Paris', 'Tokyo', 'Seoul'],
    'Score': [85, 92, 78, 95, 88]
}

df = pd.DataFrame(data, index=['p1', 'p2', 'p3', 'p4', 'p5'])

df

       Name  Age      City  Score
p1    Alice   25  New York     85
p2      Bob   30    London     92
p3  Charlie   35     Paris     78
p4    David   40     Tokyo     95
p5      Eve   45     Seoul     88

In [ ]:
# 인덱스 이름(레이블)이 p2인 사람의 'City' 정보를 가져오려면? .loc를 사용하여 코드를 한 줄로 작성

'London'

In [ ]:
# 데이터프레임의 첫 번째 행부터 세 번째 행까지만 선택하려면? .iloc를 사용하여 코드를 한 줄로 작성

       Name  Age      City  Score
p1    Alice   25  New York     85
p2      Bob   30    London     92
p3  Charlie   35     Paris     78

In [ ]:
# Score가 90점 이상인 데이터들만 필터링하여 전체 컬럼을 출력하려면?

     Name  Age    City  Score
p2    Bob   30  London     92
p4  David   40   Tokyo     95

In [ ]:
# 나이가 35세 이상인 사람들의 Name과 Score 컬럼을 출력하려면?

       Name  Score
p3  Charlie     78
p4    David     95
p5      Eve     88

In [ ]:

# df.loc['p2', 'City']
# df.iloc[0:3]
# df[df['Score'] >= 90]
# df[df['Age'] >= 35][['Name', 'Score']]